apiVersion: v2
description: Library Helm chart for base Kubernetes resources
name: base
type: library
version: 0.1.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.x.x
