# CI workflow for linting and testing Helm charts on pull requests
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CT_TARGET_BRANCH: ${{ github.event.repository.default_branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ct lint requires Python 3.x to run following packages:
      #  - yamale (https://github.com/23andMe/Yamale)
      #  - yamllint (https://github.com/adrienverge/yamllint)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: azure/setup-helm@v4
      - uses: helm/chart-testing-action@v2
        with:
          version: v3.12.0

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --excluded-charts base)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install
